# Generated by Django 3.2.9 on 2024-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=16)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('ocr_time', models.FloatField()),
            ],
        ),
    ]
