# Generated by Django 3.2.9 on 2024-02-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrlog',
            old_name='title',
            new_name='origin',
        ),
        migrations.AlterField(
            model_name='ocrlog',
            name='target',
            field=models.CharField(max_length=32),
        ),
    ]
