# Generated by Django 3.1.4 on 2024-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240329_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': '昆虫详情', 'verbose_name_plural': '昆虫详情'},
        ),
        migrations.AddField(
            model_name='object',
            name='classes',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='种类'),
        ),
        migrations.AddField(
            model_name='object',
            name='family',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='科'),
        ),
        migrations.AddField(
            model_name='object',
            name='feeding_habits',
            field=models.TextField(blank=True, verbose_name='食性'),
        ),
        migrations.AddField(
            model_name='object',
            name='gender',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='属'),
        ),
        migrations.AddField(
            model_name='object',
            name='head',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='目'),
        ),
        migrations.AddField(
            model_name='object',
            name='latin_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='拉丁名称'),
        ),
        migrations.AlterField(
            model_name='object',
            name='detail',
            field=models.TextField(blank=True, verbose_name='分布区域'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(choices=[('稻纵卷叶螟', '稻纵卷叶螟'), ('稻叶毛虫', '稻叶毛虫'), ('稻潜叶蝇', '稻潜叶蝇'), ('水稻二化螟', '水稻二化螟'), ('水稻三化螟', '水稻三化螟'), ('稻瘿蚊', '稻瘿蚊'), ('稻秆蝇', '稻秆蝇'), ('褐稻虱', '褐稻虱'), ('白背飞虱', '白背飞虱'), ('灰飞虱', '灰飞虱'), ('稻水象甲', '稻水象甲'), ('稻叶蝉', '稻叶蝉'), ('谷物撒布机蓟马', '谷物撒布机蓟马'), ('稻苞虫', '稻苞虫'), ('蛴螬', '蛴螬'), ('蝼蛄', '蝼蛄'), ('金针虫', '金针虫'), ('白边蛾', '白边蛾'), ('小地老虎', '小地老虎'), ('大地老虎', '大地老虎'), ('黄地老虎', '黄地老虎'), ('红蜘蛛', '红蜘蛛'), ('玉米螟', '玉米螟'), ('夜蛾', '夜蛾'), ('蚜虫', '蚜虫'), ('白星花金龟', '白星花金龟'), ('桃蛀螟', '桃蛀螟'), ('麦长管蚜', '麦长管蚜'), ('麦二叉蚜', '麦二叉蚜'), ('燕麦蚜', '燕麦蚜'), ('麦红吸浆虫', '麦红吸浆虫'), ('小麦红蜘蛛', '小麦红蜘蛛'), ('长腿蜘蛛螨', '长腿蜘蛛螨'), ('小麦根皮蓟马', '小麦根皮蓟马'), ('麦叶蜂', '麦叶蜂'), ('麦黑斑潜叶蝇', '麦黑斑潜叶蝇'), ('甜菜潜叶蝇', '甜菜潜叶蝇'), ('跳甲', '跳甲'), ('甘蓝夜蛾', '甘蓝夜蛾'), ('甜菜夜蛾', '甜菜夜蛾'), ('甜菜斑蝇', '甜菜斑蝇'), ('草地螟', '草地螟'), ('甜菜象虫', '甜菜象虫'), ('东方绢金龟', '东方绢金龟'), ('苜蓿叶象甲', '苜蓿叶象甲'), ('苜蓿夜蛾', '苜蓿夜蛾'), ('苜蓿盲蝽', '苜蓿盲蝽'), ('牧草盲蝽', '牧草盲蝽'), ('蝗总科', '蝗总科'), ('磨光东鳖甲', '磨光东鳖甲'), ('豆科水疱甲虫', '豆科水疱甲虫'), ('水疱甲虫', '水疱甲虫'), ('苜蓿斑蚜', '苜蓿斑蚜'), ('牛角花齿蓟马', '牛角花齿蓟马'), ('蓟马', '蓟马'), ('苜蓿广肩小蜂', '苜蓿广肩小蜂'), ('东方菜粉蝶', '东方菜粉蝶'), ('绿盲蝽', '绿盲蝽'), ('刺蛾科', '刺蛾科'), ('葡萄根瘤蚜', '葡萄根瘤蚜'), ('葡萄缺节瘿螨', '葡萄缺节瘿螨'), ('南天竹刘氏短须螨', '南天竹刘氏短须螨'), ('十星叶甲', '十星叶甲'), ('侧多食附线螨', '侧多食附线螨'), ('康氏粉蚧', '康氏粉蚧'), ('葡萄透翅蛾', '葡萄透翅蛾'), ('萄葡天蛾', '萄葡天蛾'), ('斑衣蜡蝉', '斑衣蜡蝉'), ('四带虎天牛', '四带虎天牛'), ('大青叶蝉', '大青叶蝉'), ('盲蝽科', '盲蝽科'), ('温室粉虱', '温室粉虱'), ('斑叶蝉', '斑叶蝉'), ('柑橘凤蝶', '柑橘凤蝶'), ('柑橘红蜘蛛', '柑橘红蜘蛛'), ('柑橘锈螨', '柑橘锈螨'), ('吹绵蚧', '吹绵蚧'), ('矢尖蚧', '矢尖蚧'), ('红蜡蚧', '红蜡蚧'), ('黑褐圆盾蚧', '黑褐圆盾蚧'), ('黑点介壳虫', '黑点介壳虫'), ('堆蜡粉蚧', '堆蜡粉蚧'), ('黑刺粉虱', '黑刺粉虱'), ('柑橘大实蝇', '柑橘大实蝇'), ('芒果柑桔小实蝇', '芒果柑桔小实蝇'), ('蜜柑大实蝇', '蜜柑大实蝇'), ('斜纹夜蛾', '斜纹夜蛾'), ('枯叶夜蛾', '枯叶夜蛾'), ('柑桔潜叶蛾', '柑桔潜叶蛾'), ('花椒蚜虫', '花椒蚜虫'), ('茶蚜', '茶蚜'), ('绣线菊蚜', '绣线菊蚜'), ('茶黄蓟马', '茶黄蓟马'), ('荔枝叶瘿蚊', '荔枝叶瘿蚊'), ('白翅蜡蝉', '白翅蜡蝉'), ('褐缘蛾蜡蝉', '褐缘蛾蜡蝉'), ('芒果切叶象甲', '芒果切叶象甲'), ('横线尾夜蛾', '横线尾夜蛾'), ('叶蝉', '叶蝉'), ('脊胸天牛', '脊胸天牛'), ('芒果果肉象甲', '芒果果肉象甲'), ('叶蝉科', '叶蝉科')], max_length=32, unique=True, verbose_name='名字'),
        ),
    ]
